# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en_core_web_lg #en_core_web_md

pipeline:
# # Configuration for Rasa NLU pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
# # Spacy is useful for detecting common entities like city_name
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer # One-hot encode all tokens
  - name: CountVectorsFeaturizer # Make character n-grams
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 1024
    model_confidence: cosine # Recommended to set it to `cosine` (`cosine` will be deafult in 3.0.0)
    loss_type: cross_entropy # `softmax` is deprecated, use `cross_entropy` instead (`softmax` will be removed in 3.0.0)
    constrain_similarities: True # Recommended to set it to `True` when using cross-entropy loss (`True` will be deafult in 3.0.0)
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 512
    model_confidence: cosine # Recommended to set it to `cosine` (`cosine` will be deafult in 3.0.0)
    loss_type: cross_entropy # `softmax` is deprecated, use `cross_entropy` instead (`softmax` will be removed in 3.0.0)
    constrain_similarities: True # Recommended to set it to `True` when using cross-entropy loss (`True` will be deafult in 3.0.0)
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # Configuration for Rasa Core policies
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 256
    model_confidence: cosine # Recommended to set it to `cosine` (`cosine` will be deafult in 3.0.0)
    loss_type: cross_entropy # `softmax` is deprecated, use `cross_entropy` instead (`softmax` will be removed in 3.0.0)
    constrain_similarities: True # Recommended to set it to `True` when using cross-entropy loss (`True` will be deafult in 3.0.0)
  - name: RulePolicy
