# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en_core_web_md #en_core_web_lg

pipeline:
# # Configuration for Rasa NLU pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
# # Spacy is useful for detecting common entities like city_name
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer # One-hot encode all tokens
  - name: CountVectorsFeaturizer # Make character n-grams
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 1024
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 512
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # Configuration for Rasa Core policies
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 256
  - name: RulePolicy
