language: en
pipeline:
- name: SpacyNLP
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 128
  model_confidence: cosine
  loss_type: cross_entropy
  constrain_similarities: true
  evaluate_on_number_of_examples: 0
  evaluate_every_number_of_epochs: 5
  tensorboard_log_directory: ./tensorboard
  tensorboard_log_level: epoch
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 128
  model_confidence: cosine
  loss_type: cross_entropy
  constrain_similarities: true
  evaluate_on_number_of_examples: 0
  evaluate_every_number_of_epochs: 5
  tensorboard_log_directory: ./tensorboard
  tensorboard_log_level: epoch
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1
policies:
- name: AugmentedMemoizationPolicy
- name: TEDPolicy
  max_history: 8
  epochs: 128
  model_confidence: cosine
  loss_type: cross_entropy
  constrain_similarities: true
  evaluate_on_number_of_examples: 0
  evaluate_every_number_of_epochs: 5
  tensorboard_log_directory: ./tensorboard
  tensorboard_log_level: epoch
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: true
