language: en_core_web_md
pipeline:
- name: SpacyNLP
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: RegexFeaturizer
  case_sensitive: false
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 201
  model_confidence: linear_norm
  loss_type: cross_entropy
  constrain_similarities: true
  evaluate_on_number_of_examples: 200
  evaluate_every_number_of_epochs: 5
  tensorboard_log_directory: ./.tensorboard
  tensorboard_log_level: epoch
- name: RegexEntityExtractor
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 41
  model_confidence: linear_norm
  loss_type: cross_entropy
  constrain_similarities: true
  evaluate_on_number_of_examples: 5
  evaluate_every_number_of_epochs: 1
  tensorboard_log_directory: ./.tensorboard
  tensorboard_log_level: epoch
- name: FallbackClassifier
  threshold: 0.5
  ambiguity_threshold: 0.1
policies:
- name: AugmentedMemoizationPolicy
- name: TEDPolicy
  max_history: 8
  epochs: 71
  model_confidence: linear_norm
  loss_type: cross_entropy
  constrain_similarities: true
  evaluate_on_number_of_examples: 200
  evaluate_every_number_of_epochs: 5
  tensorboard_log_directory: ./.tensorboard
  tensorboard_log_level: epoch
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: true
